apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microbin-pv-claim
  namespace: microbin
  labels:
    app: microbin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
