apiVersion: v1
kind: Service
metadata:
  name: microbin
  namespace: microbin
  labels:
    app: microbin
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: microbin
  clusterIP: None